project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Simulations"
        contents:
          - predator-prey.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



